import { useMemo,useState } from "react";
import { Check,ChevronLeft,Home,MapPin,Plus,Trash2 } from "lucide-react";
import { Link,Navigate } from "react-router-dom";
import { useAuth } from "../features/auth/AuthProvider";
import { useDelivery } from "../features/delivery/DeliveryProvider";

export default function DeliveryAddressesPage(){
 const {session}=useAuth(); const {state,addCourierAddress,removeLocation,setDefaultLocation}=useDelivery();
 const [form,setForm]=useState(false); const [label,setLabel]=useState("Дом"); const [region,setRegion]=useState(""); const [city,setCity]=useState(""); const [street,setStreet]=useState(""); const [house,setHouse]=useState(""); const [apartment,setApartment]=useState(""); const [postalCode,setPostalCode]=useState(""); const [comment,setComment]=useState(""); const [error,setError]=useState<string|null>(null); const [saving,setSaving]=useState(false);
 const user=session.user; const list=useMemo(()=>state.locations.filter((item)=>item.type === "courier").sort((a,b)=>Number(b.isDefault)-Number(a.isDefault)),[state.locations]);
 if(!session.isAuthenticated||!user)return <Navigate to="/auth" replace/>;
 const customerName=user.name; const customerPhone=user.phone;
 async function save(e:React.FormEvent){e.preventDefault();if(!city.trim()||!street.trim()||!house.trim()){setError("Укажите город, улицу и дом.");return;}setSaving(true);setError(null);try{await addCourierAddress({type:"courier",label:label.trim()||"Адрес",recipient:{name:customerName,phone:customerPhone},region:region.trim(),city:city.trim(),street:street.trim(),house:house.trim(),apartment:apartment.trim(),postalCode:postalCode.trim(),comment:comment.trim()});setForm(false);setCity("");setStreet("");setHouse("");setApartment("");setPostalCode("");setComment("");}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить адрес");}finally{setSaving(false);}}
 return <div className="delivery-page">
  <header className="delivery-page__header"><Link to="/profile" className="delivery-page__back"><ChevronLeft size={22}/></Link><div><h1>Адреса доставки</h1><p>Курьерские адреса из профиля покупателя</p></div></header>
  {!form&&<><section className="delivery-locations"><div className="delivery-locations__header"><h2>Сохранённые адреса</h2></div>{state.isLoading?<div className="delivery-empty"><p>Загрузка адресов…</p></div>:list.length===0?<div className="delivery-empty"><MapPin size={34}/><h3>Адресов пока нет</h3><p>Добавьте адрес для курьерской доставки.</p></div>:<div className="delivery-location-list">{list.map(a=><article key={a.id} className="delivery-location-card"><div className="delivery-location-card__icon"><Home size={21}/></div><div className="delivery-location-card__content"><div className="delivery-location-card__title"><strong>{a.label}</strong>{a.isDefault&&<span>Основной</span>}</div><p>{a.city}, {a.street}, {a.house}{a.apartment?`, кв. ${a.apartment}`:""}</p><small>Получатель: {a.recipient.name}</small></div><div className="delivery-location-card__actions">{!a.isDefault&&<button type="button" onClick={()=>void setDefaultLocation(a.id)} title="Сделать основным"><Check size={18}/></button>}<button type="button" onClick={()=>void removeLocation(a.id)} title="Удалить"><Trash2 size={18}/></button></div></article>)}</div>}</section><div className="delivery-add-actions"><button type="button" onClick={()=>setForm(true)}><Plus size={19}/>Добавить адрес</button></div><p className="delivery-form-card__hint">Пункты выдачи будут загружаться из API выбранной службы доставки на этапе оформления заказа.</p></>}
  {form&&<section className="delivery-form-card"><h2>Курьерский адрес</h2><form onSubmit={save}><label><span>Название</span><input value={label} onChange={e=>setLabel(e.target.value)}/></label><label><span>Регион</span><input value={region} onChange={e=>setRegion(e.target.value)}/></label><label><span>Город</span><input value={city} onChange={e=>setCity(e.target.value)}/></label><div className="delivery-form-card__row"><label><span>Улица</span><input value={street} onChange={e=>setStreet(e.target.value)}/></label><label><span>Дом</span><input value={house} onChange={e=>setHouse(e.target.value)}/></label></div><label><span>Квартира</span><input value={apartment} onChange={e=>setApartment(e.target.value)}/></label><label><span>Индекс</span><input value={postalCode} onChange={e=>setPostalCode(e.target.value)}/></label><label><span>Комментарий курьеру</span><textarea value={comment} onChange={e=>setComment(e.target.value)} rows={3}/></label>{error&&<p className="delivery-form-card__error">{error}</p>}<div className="delivery-form-card__actions"><button type="submit" disabled={saving}>{saving?"Сохранение…":"Сохранить адрес"}</button><button type="button" onClick={()=>setForm(false)}>Отмена</button></div></form></section>}
 </div>;
}
