import type { Request, Response } from "express";
import { Prisma } from "../../../generated/prisma/client.js";
import { homeBannerInputSchema,homeBannerUpdateSchema,homeBannerParamsSchema,articleInputSchema,articleUpdateSchema,articleParamsSchema } from "./moderator-home-content.schemas.js";
import { listModeratorHomeBanners,createModeratorHomeBanner,updateModeratorHomeBanner,deleteModeratorHomeBanner,listModeratorArticles,createModeratorArticle,updateModeratorArticle,deleteModeratorArticle } from "./moderator-home-content.service.js";
const bad=(res:Response,details:any)=>res.status(400).json({error:{code:"INVALID_CONTENT_DATA",message:"Некорректные данные",details}});
export async function listHomeBannersAdmin(_r:Request,res:Response){res.json({data:await listModeratorHomeBanners()});}
export async function createHomeBannerAdmin(req:Request,res:Response){const p=homeBannerInputSchema.safeParse(req.body);if(!p.success){bad(res,p.error.flatten());return;}try{res.status(201).json({data:await createModeratorHomeBanner(p.data)});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2003"){res.status(404).json({error:{code:"COLLECTION_NOT_FOUND",message:"Подборка не найдена"}});return;}throw e;}}
export async function updateHomeBannerAdmin(req:Request,res:Response){const a=homeBannerParamsSchema.safeParse(req.params),p=homeBannerUpdateSchema.safeParse(req.body);if(!a.success){bad(res,a.error.flatten());return;}if(!p.success){bad(res,p.error.flatten());return;}try{res.json({data:await updateModeratorHomeBanner(a.data.bannerId,p.data)});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2025"){res.status(404).json({error:{code:"BANNER_NOT_FOUND",message:"Hero не найден"}});return;}throw e;}}
export async function deleteHomeBannerAdmin(req:Request,res:Response){const a=homeBannerParamsSchema.safeParse(req.params);if(!a.success){bad(res,a.error.flatten());return;}try{await deleteModeratorHomeBanner(a.data.bannerId);res.json({data:{bannerId:a.data.bannerId,deleted:true}});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2025"){res.status(404).json({error:{code:"BANNER_NOT_FOUND",message:"Hero не найден"}});return;}throw e;}}
export async function listArticlesAdmin(_r:Request,res:Response){res.json({data:await listModeratorArticles()});}
export async function createArticleAdmin(req:Request,res:Response){const p=articleInputSchema.safeParse(req.body);if(!p.success){bad(res,p.error.flatten());return;}try{res.status(201).json({data:await createModeratorArticle(p.data)});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2002"){res.status(409).json({error:{code:"ARTICLE_SLUG_EXISTS",message:"Статья с таким slug уже существует"}});return;}throw e;}}
export async function updateArticleAdmin(req:Request,res:Response){const a=articleParamsSchema.safeParse(req.params),p=articleUpdateSchema.safeParse(req.body);if(!a.success){bad(res,a.error.flatten());return;}if(!p.success){bad(res,p.error.flatten());return;}try{res.json({data:await updateModeratorArticle(a.data.articleId,p.data)});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2025"){res.status(404).json({error:{code:"ARTICLE_NOT_FOUND",message:"Статья не найдена"}});return;}if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2002"){res.status(409).json({error:{code:"ARTICLE_SLUG_EXISTS",message:"Статья с таким slug уже существует"}});return;}throw e;}}
export async function deleteArticleAdmin(req:Request,res:Response){const a=articleParamsSchema.safeParse(req.params);if(!a.success){bad(res,a.error.flatten());return;}try{await deleteModeratorArticle(a.data.articleId);res.json({data:{articleId:a.data.articleId,deleted:true}});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2025"){res.status(404).json({error:{code:"ARTICLE_NOT_FOUND",message:"Статья не найдена"}});return;}throw e;}}
