import {ArrowLeft,Save,ShoppingBag,Trash2} from "lucide-react";
import {useEffect,useState} from "react";
import {useNavigate,useParams} from "react-router-dom";
import {deleteAdminCustomer,getAdminCustomer,updateAdminCustomer} from "../../shared/api/admin";
import type{AdminCustomerDetails}from"../../shared/api/admin";
const money=(v:string|number)=>`${new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(Number(v)||0)} ₽`;
const date=(v:string)=>new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
export default function AdminCustomerEditPage(){
 const{id}=useParams(),nav=useNavigate(),[c,setC]=useState<AdminCustomerDetails|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState(false),[error,setError]=useState(""),[msg,setMsg]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[username,setUsername]=useState(""),[birth,setBirth]=useState("");
 const load=async()=>{if(!id)return;setLoading(true);try{const r=await getAdminCustomer(id);setC(r.data);setName(r.data.name??"");setPhone(r.data.phone??"");setEmail(r.data.email??"");setUsername(r.data.username??"");setBirth(r.data.birth_date?r.data.birth_date.slice(0,10):"")}catch{setError("Не удалось загрузить покупателя.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[id]);
 const save=async()=>{if(!c)return;setBusy(true);setError("");setMsg("");try{await updateAdminCustomer(c.id,{name:name.trim()||null,phone:phone.trim()||null,email:email.trim()||null,username:username.trim()||null,birthDate:birth||null});setMsg("Данные покупателя сохранены.");await load()}catch{setError("Не удалось сохранить. Проверьте уникальность email и телефона.")}finally{setBusy(false)}};
 const remove=async()=>{if(!c)return;const ok=window.confirm(`Удалить покупателя «${c.name||c.email||"Без имени"}»?\n\nАккаунт, адреса, избранное, сессии и бонусные данные будут удалены. История оформленных заказов сохранится.`);if(!ok)return;setDeleting(true);setError("");try{const r=await deleteAdminCustomer(c.id);window.alert(`Покупатель удалён. Сохранено заказов в истории: ${r.data.preservedOrders}.`);nav("/admin/customers",{replace:true})}catch{setError("Не удалось удалить покупателя.");setDeleting(false)}};
 if(loading)return <div className="admin-products-state">Загрузка покупателя…</div>;
 if(!c)return <div className="admin-editor-message is-error">{error||"Покупатель не найден."}</div>;
 return <section className="admin-customer-edit"><button className="admin-order-back-link" onClick={()=>nav("/admin/customers")}><ArrowLeft size={18}/>Покупатели</button><div className="admin-page-heading"><div><h1>{c.name||"Покупатель"}</h1><p>{c.email||c.phone||"Без контактов"} · зарегистрирован {date(c.created_at)}</p></div></div>{msg&&<div className="admin-editor-message is-success">{msg}</div>}{error&&<div className="admin-editor-message is-error">{error}</div>}<div className="admin-customer-layout"><main><section className="admin-editor-card"><h2>Данные покупателя</h2><div className="admin-form-grid"><label className="admin-field"><span>ФИО</span><input value={name} onChange={e=>setName(e.target.value)}/></label><label className="admin-field"><span>Email</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="admin-field"><span>Телефон</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Необязательно"/></label><label className="admin-field"><span>Telegram</span><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username"/></label><label className="admin-field"><span>Дата рождения</span><input type="date" value={birth} onChange={e=>setBirth(e.target.value)}/></label></div><button className="admin-primary-button admin-customer-save" disabled={busy||deleting} onClick={save}><Save size={16}/>{busy?"Сохранение…":"Сохранить"}</button></section><section className="admin-editor-card"><h2>Адреса доставки</h2>{!c.customer_addresses.length?<p>Сохранённых адресов нет.</p>:<div className="admin-customer-addresses">{c.customer_addresses.map(a=><div key={a.id}><div><strong>{a.address_name}{a.is_default?" · основной":""}</strong><span>{a.recipient_name} · {a.phone}</span></div><p>{[a.region,a.city,a.street,a.house,a.apartment&&`кв. ${a.apartment}`,a.postal_code].filter(Boolean).join(", ")}</p>{a.comment&&<small>{a.comment}</small>}</div>)}</div>}</section><section className="admin-editor-card admin-customer-danger"><h2>Удаление покупателя</h2><p>Аккаунт и персональные данные профиля будут удалены. Оформленные заказы останутся в истории магазина без связи с аккаунтом.</p><button className="admin-danger-button" disabled={busy||deleting} onClick={remove}><Trash2 size={16}/>{deleting?"Удаление…":"Удалить покупателя"}</button></section></main><aside><section className="admin-editor-card"><h2>Заказы</h2>{!c.orders.length?<div className="admin-products-state"><ShoppingBag size={26}/><span>Заказов пока нет</span></div>:<div className="admin-customer-orders">{c.orders.map(o=><button key={o.id} onClick={()=>nav(`/admin/orders/${encodeURIComponent(o.order_number)}`)}><span><strong>№ {o.order_number}</strong><small>{date(o.ordered_at)} · {o.status}</small></span><strong>{money(o.total_amount)}</strong></button>)}</div>}</section></aside></div></section>
}
