import { ChevronLeft, ChevronRight, Search, ShoppingBag } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { useNavigate } from "react-router-dom";
import { getAdminOrders } from "../../shared/api/admin";
import type { AdminOrderArchiveFilter, AdminOrderListItem, AdminOrderStatus } from "../../shared/api/admin";

const labels:Record<string,string>={new:"Новый",confirmed:"Подтверждён",processing:"В обработке",shipped:"Отправлен",completed:"Завершён",cancelled:"Отменён",unpaid:"Не оплачен",pending:"Ожидает",paid:"Оплачен",failed:"Ошибка",refunded:"Возврат",preparing:"Готовится",handed_over:"Передан",in_transit:"В пути",delivered:"Доставлен",returned:"Возвращён"};
const money=(v:string|number)=>`${new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(Number(v)||0)} ₽`;
const date=(v:string)=>new Intl.DateTimeFormat("ru-RU",{dateStyle:"short",timeStyle:"short"}).format(new Date(v));
export default function AdminOrdersPage(){
 const navigate=useNavigate(); const[items,setItems]=useState<AdminOrderListItem[]>([]); const[page,setPage]=useState(1); const[pages,setPages]=useState(1); const[total,setTotal]=useState(0); const[input,setInput]=useState(""); const[search,setSearch]=useState(""); const[status,setStatus]=useState<"all"|AdminOrderStatus>("all"); const[archive,setArchive]=useState<AdminOrderArchiveFilter>("active"); const[loading,setLoading]=useState(true); const[error,setError]=useState("");
 const query=useMemo(()=>({page,limit:20,archive,...(search?{search}:{}),...(status!=="all"?{status}:{})}),[page,search,status,archive]);
 useEffect(()=>{let live=true;setLoading(true);setError("");getAdminOrders(query).then(r=>{if(!live)return;setItems(r.data);setTotal(r.pagination.total);setPages(Math.max(1,r.pagination.totalPages))}).catch(()=>live&&setError("Не удалось загрузить заказы.")).finally(()=>live&&setLoading(false));return()=>{live=false}},[query]);
 const submit=(e:FormEvent)=>{e.preventDefault();setPage(1);setSearch(input.trim())};
 return <section className="admin-orders-page"><div className="admin-page-heading"><div><h1>Заказы</h1><p>Все заказы магазина, их оплата и доставка.</p></div></div>
 <div className="admin-orders-toolbar"><form className="admin-products-search" onSubmit={submit}><Search size={18}/><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Номер, имя, телефон или email"/><button>Найти</button></form><label><span>Статус заказа</span><select value={status} onChange={e=>{setStatus(e.target.value as typeof status);setPage(1)}}><option value="all">Все</option><option value="new">Новые</option><option value="confirmed">Подтверждённые</option><option value="processing">В обработке</option><option value="shipped">Отправленные</option><option value="completed">Завершённые</option><option value="cancelled">Отменённые</option></select></label><label><span>Раздел</span><select value={archive} onChange={e=>{setArchive(e.target.value as AdminOrderArchiveFilter);setPage(1)}}><option value="active">Активные</option><option value="archived">Архив</option><option value="all">Все</option></select></label></div>
 {error&&<div className="admin-editor-message is-error">{error}</div>}<div className="admin-products-summary"><strong>{total}</strong><span>заказов найдено</span></div>
 <div className="admin-orders-table-card">{loading?<div className="admin-products-state">Загрузка заказов…</div>:!items.length?<div className="admin-products-state"><ShoppingBag size={30}/><strong>Заказы не найдены</strong><span>Измените поиск или фильтр.</span></div>:<div className="admin-orders-table-wrap"><table className="admin-orders-table"><thead><tr><th>Заказ</th><th>Покупатель</th><th>Сумма</th><th>Заказ</th><th>Оплата</th><th>Доставка</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td data-label="Заказ"><strong>№ {x.order_number}</strong>{x.is_archived&&<span className="admin-order-archive-mark">Архив</span>}<small>{date(x.ordered_at)}</small></td><td data-label="Покупатель"><strong>{x.customer_name}</strong><small>{x.phone}</small></td><td data-label="Сумма"><strong>{money(x.total_amount)}</strong><small>{x.order_items.length} поз.</small></td><td data-label="Заказ"><span className={`admin-order-badge is-${x.status}`}>{labels[x.status]??x.status}</span></td><td data-label="Оплата"><span className={`admin-order-badge is-${x.payment_status}`}>{labels[x.payment_status]??x.payment_status}</span></td><td data-label="Доставка"><span>{x.order_deliveries?labels[x.order_deliveries.status]??x.order_deliveries.status:"—"}</span><small>{x.order_deliveries?.delivery_methods.name??""}</small></td><td className="admin-orders-actions"><button className="admin-secondary-button" onClick={()=>navigate(`/admin/orders/${encodeURIComponent(x.order_number)}`)}>Открыть</button></td></tr>)}</tbody></table></div>}</div>
 {pages>1&&<div className="admin-products-pagination"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/>Назад</button><span>Страница {page} из {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Далее<ChevronRight size={17}/></button></div>}</section>
}
